setwd("D:\\Coursera\\data")
ColNames <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
temp <- read.table("./household_power_consumption.txt",header = T,sep = ";",skip = 66636,nrows = 2880,col.names = ColNames)
temp$Date <- as.Date(temp$Date,format = "%d/%m/%Y")
temp$Time <- strptime(paste(temp$Date,temp$Time,sep = ' '),format = "%Y-%m-%d %H:%M:%S")
png(filename = "./plot1.png",width = 480,height = 480)
hist(x = temp$Global_active_power,freq = T,col = "red",main = "Global Active Power",xlab = "Global Active Power(kilowatts)")
# dev.copy(device = png,file = "./plot1.png", width = 480,height = 480)
dev.off()
