setwd("D:\\Coursera\\data")
ColNames <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
temp <- read.table("./household_power_consumption.txt",header = T,sep = ";",skip = 66636,nrows = 2880,col.names = ColNames)
temp$Date <- as.Date(temp$Date,format = "%d/%m/%Y")
temp$Time <- strptime(paste(temp$Date,temp$Time,sep = ' '),format = "%Y-%m-%d %H:%M:%S")
png(filename = "./plot4.png",width = 480,height = 480)
par(mfrow = c(2,2))
plot(x = temp$Time,y = temp$Global_active_power,type = 'l',ylab = "Global Active Power(kilowatts)",xlab = "")
plot(x = temp$Time,y = temp$Voltage,type = 'l',ylab = "Voltage",xlab = "datetime")
plot(temp$Time,temp$Sub_metering_1,type = 'l',ylab = "Energy sub metering",xlab = "")
lines(temp$Time,temp$Sub_metering_2,col = "red",xlab = "")
lines(temp$Time,temp$Sub_metering_3,col = "blue",xlab = "")
legend("topright",lty=c(1,1,1),col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty = "n")
plot(x = temp$Time,y = temp$Global_reactive_power,type = 'l',ylab = "Global_reactive_power",xlab = "datetime")
# dev.copy(device = png,file = "./plot4.png", width = 480,height = 480)
dev.off()
